// <auto-generated />
using System;
using ECAN_INVOICE.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECAN_INVOICE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240701204541_two")]
    partial class two
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ECAN_INVOICE.Models.Product", b =>
                {
                    b.Property<string>("strId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("DaliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfPurchase")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceivedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("S_No")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("strId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ECAN_INVOICE.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("pasword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
